WAM2layers/WAM2layers

.gitignore
Backtrack_savedaily_mat.py
Con_E_Recyc_Output_monthly_mat.py
Fluxes_and_States_mat.py
Hor_Fluxes_Output_mat.py
environment.yml
getconstants_pressure_ECEarth.py

* Align the code with #23 
* Add environment file
* Upgrade to python 3
* Apply code formatters (black and isort) for consistent formatting
* Add .gitignore (to help prevent accidentally committing non-source files)
closes #7
refs #13
Since this is the first time the code formatters are applied, it leads to a very large diff that is difficult to review. On the flipside, future diffs will be much cleaner. For reviewing this PR, it is easiest to view the commits one at a time (start [here](https://github.com/WAM2layers/WAM2layers/pull/25/commits/92b6584a616f3e2b57d7881c2045404529108f87) and click next). For the big formatting changes, you don't have to check every line, since there are no code changes in those commits, only formatting.

Use Python 3, apply code formatters, add .gitignore and environment.yml

---

Backtrack_savedaily_mat.py
Fluxes_and_States_mat.py
cases/example.yaml
environment.yml

- Add a folder called "cases" with an example config file in it
- Load the config in "Fluxes_and_states..." and "Backtrack_savedaily..." instead of hardcoded settings
- Rename some config settings to more generic names
- Change config settings that have 1 or 0 as value to true or false
closes #15 
Note: includes changes from #25, so the diff is very big. Only the last 2 commits belong to this PR. After merging #25 this one is much easier to review.

Separate config from code

---

Fluxes_and_States_mat.py

Simplify paths

---

environment.yml

fix environment

---

cases/era5_2013.yaml
preprocess_era5.py

Add coordinates to output and clarify time variables

---

cases/era5_2013.yaml
preprocess_era5.py

restructured settings file

---

cases/era5_2013.yaml
preprocess_era5.py
preprocessing.py

inserted periodic boundary option
+ fixed data path typo missing "/"

periodic boundary + typo

---

cases/era5_2013.yaml
preprocess_era5.py
preprocessing.py

Reverts WAM2layers/WAM2layers#56
because it had not been reviewed yet

Revert "periodic boundary + typo"

---

preprocess_era5.py
preprocess_era5_modellevels.py

Added script that reads in model level data ERA5

Added preprocess file ERA5 handles model levels

---

README.md
preprocess_era5.py

Fix a bug in era5 preproc script

correct evap and precip

---

preprocess_era5.py
preprocessing.py

linked the stability factor vertical to kvf in config

linked the stability factor vertical to kvf in config

---

preprocess_era5_modellevels.py

Draft pull request
Still to do:
- add comments with units inline

Era5 modellevels

---

tests/test_pressure.py

This adds a minimal example to insert certain levels of interest into pressure-level data. I think it can be used to replace the loops in the target PR.
I think it can still be polished a bit more, but this should be a good start. @ruudvdent can you please have a good look at it and see if it works for you? Perhaps you can have a go with it in your PR?
NOTE: this is a PR to your feature branch, not to master.

Add minimal example avoiding loops

---

backtrack.py
preprocess_era5.py
preprocess_era5_modellevels.py
preprocessing.py

This saves a lot of disk space for the pre-processed data.
Changed a lot of variable names as they were not consistent between preprocessing and backtracking
closes #68

Move resampling and vertical flux calculation to tracking code

---

docs/preprocessing.md
wam2layers/preprocessing/checks.py
wam2layers/preprocessing/preprocess_era5.py
wam2layers/preprocessing/preprocess_era5_modellevels.py
wam2layers/tracking/backtrack.py

This adds several utility functions to check all kinds of things related to (pre-processed) data. Several aspects are up for discussion:
* Should we issue warnings or raise exceptions?
* How to deal with different notations of units?
* Do we agree on the current characteristics of input data, as summarized at the bottom of `preprocessing/checks.py`?
* What to do with the extra midnight timestamp?
To do:
Updated documentation: https://wam2layers--113.org.readthedocs.build/en/113/preprocessing.html

Add functions to check pre-processed data

---

docs/preprocessing.md
wam2layers/preprocessing/checks.py
wam2layers/preprocessing/preprocess_era5.py
wam2layers/preprocessing/preprocess_era5_modellevels.py
wam2layers/tracking/backtrack.py

Started an attempt to sync preprocessing for model- and pressure levels. Work in progress.
In the process, I moved all unit changes to the tracking (insofar that was not done yet).
Notes:
- pressure levels are descending, model levels ascending?
- level dimension is called "lev" in one file and "level" in the other
- copied total column water correction so it is the same in both files

Synchronize preproc for pressure and model levels

---

docs/quickstart.md

Recommend editable installation including conda env and source code clone.

Better quickstart

---

scripts/download_era5_ml.py
scripts/download_era5_pl.py

leading zeros and daily folders, so that you get `2020/01/01/ERA5_2020-01-01_d2m.nc` etc.

Some small tweaks to the download scripts

---

scripts/download_era5_ml.py
scripts/download_era5_pl.py

I changed two things on the downloading scripts as indicated in the commits, as I discovered mean sea level pressure instead of surface pressure was downloaded, and the naming of the file was not entirely correct

Corrected mistake downloadscript

---

cases/era5_2013.yaml
cases/era5_2021.yaml
src/wam2layers/preprocessing/era5.py

Use updated filename pattern for raw input data in preprocessing and config

Filename template

---

scripts/download_era5_ml.py
src/wam2layers/config.py
src/wam2layers/preprocessing/era5.py
src/wam2layers/tracking/backtrack.py

What happened in this pull request.
Changed preprocess script and backtrack script such that the start and end date are included in preprocessing.
Changed backtrack script such that event tracking can be done per hour instead of per day.
Closes #155 
Fixed issue that the main was broken. Used history to reset to preprocess correctly (integration of two layers)
Fixes #177

Correction in integration of two layers + correct start and end date including clear documentation

---

CHANGELOG.md
docs/develop.md
pyproject.toml

Add developer documentation

---

README.md

This PR adds a movie at the top of the README, to illustrate the concept of moisture tracking

Add movie to README

---

.github/ISSUE_TEMPLATE/standard-issue-template.md

To see how the web interface formats them

Try out issue template

---

src/wam2layers/tracking/backtrack.py

Proper ending

---

.github/DISCUSSION_TEMPLATE/ideas.yml

fix label key

---

.github/DISCUSSION_TEMPLATE/ideas.yml
.github/DISCUSSION_TEMPLATE/q&a.yml
.github/DISCUSSION_TEMPLATE/show-and-tell.yml

All should work now! Please review!

updated discussion templates

---

docs/index.md
src/wam2layers/analysis/visualization.py

Fixed error in output frequency

---

.github/DISCUSSION_TEMPLATE/q&a.yml

small adjustment to readme link

Discussion templates

---

src/wam2layers/tracking/backtrack.py

No colon in output file

---

docs/installation.md

This is generally faster and fixes hdf5 issues with dask

Recommend python 3.11 in installation docs

---

src/wam2layers/config.py
src/wam2layers/preprocessing/era5.py
src/wam2layers/preprocessing/shared.py
src/wam2layers/preprocessing/xarray_append.py

Logging in preprocessing on the use of total column water from ERA5 to correct column water vapour to column water
close #279 will be resolved with this pull request

Logging in preprocessing

---

CITATION.cff
README.md

Tiny readme updates and added new contributors

Readme and citation

---

docs/userguide.md

typo in documentation link to config file

put_correct_link

---

CHANGELOG.md
src/wam2layers/config.py
src/wam2layers/preprocessing/shared.py
src/wam2layers/utils/profiling.py

Fix bug in profiling

---

README.md

small update to readme, refer to open-sustainable-technology Github

Readme open tech

---

example_config.yaml

log level removed and new paths

updated example_config

---

docs/userguide/preprocess.md
src/wam2layers/config.py

Closes #425 (already works, added a more detailed explanation to the docs)
Closes #421

Improve documentation (CMIP6, ARCO)

---

CHANGELOG.md
scripts/download_era5_ml.py
scripts/download_era5_pl.py
src/wam2layers/preprocessing/era5.py

Update for new CDS, new cdsapi

---

docs/develop.md

Correct release instructions

---

example_config.yaml

use correct output frequency format in example
